### PR TITLE
[WIP] Hold the YNAB client in memory between requests

### PR DESCRIPTION
**Pull request by scottrobertson**

### CODE REVIEW

**Comment by scottrobertson** [comment]
@rossdargan do you want to take a look at this? Seems to work really nicely for me. 

I don't know much Python, so there is probably a lot cleaner way to do it :D

**Comment by rossdargan** [comment]
I wonder if we should do a sync prior to a push? Might be worth seeing how much time that adds to the webhook.

**Comment by scottrobertson** [comment]
I don't think we need to, do we? Based on the comments in `pynYNAB`

**Comment by scottrobertson** [comment]
One part i am not sure on is the `expectedDelta` global. Not sure where that should be. Could just be a variable on the client?

**Comment by scottrobertson** [comment]
I have moved `expectedDelta` to the client object. @rossdargan do you know if this should be reset to 1 after each webhook?

**Comment by scottrobertson** [comment]
Ah ok. How come it was a global then?

**Comment by scottrobertson** [comment]
Ah, because it's set in the `getpayee` method. I will just reset it each time we sync for now

**Comment by rossdargan** [comment]
It was a global because I didn't know any better :-) TBH we could add to the ynab_client you created a push(isNewPayee) method?

**Comment by scottrobertson** [comment]
I just added a `payeeexists` method, and then I am setting the variable. Should be fine :)

**Pull request merged**
