### PR TITLE
Duplicate Detection

### PR DESCRIPTION
**Pull request by scottrobertson**

### CODE REVIEW

**Comment by scottrobertson** [comment]
@rossdargan what problem are you having at the moment?

**Comment by scottrobertson** [comment]
I just created this to test, and it works flawlessly:

```
def hashTransaction(transaction):
   tup = (transaction['date'], transaction['source'], transaction['imported_payee'])
   return hash(tup)

def containsDuplicate(transaction, transactions):
    itemHash = hashTransaction(transaction)
    for item in transactions:
        if (hashTransaction(item)==itemHash):
            return True
    return False

transaction_1 = {}
transaction_1["date"] = 1
transaction_1["source"] = 1
transaction_1["imported_payee"] = 1

transaction_2 = {}
transaction_2["date"] = 1
transaction_2["source"] = 1
transaction_2["imported_payee"] = 1

transaction_3 = {}
transaction_3["date"] = 1
transaction_3["source"] = 1
transaction_3["imported_payee"] = 1

if containsDuplicate(transaction_1, [transaction_2, transaction_3]):
    print 'contains duplicate'
else:
    print 'doesnt contain duplicate'

```

**Comment by scottrobertson** [comment]
@rossdargan just to note, this is how it's done in the CSV importer https://github.com/rienafairefr/pynYNAB/blob/b714999ce6a7d50870a51e0290220fe9dca06968/pynYNAB/scripts/csvimport.py#L152 not sure if that is outdated or not though.

**Comment by rossdargan** [comment]
It just doesn't work when I test it using real data... no idea why. Plus after sleeping on it I think theres probably way better ways of doing this... let me work on it :)

**Comment by rossdargan** [comment]
Ok, the issue is with pynynab. Existing transactions loaded are all rounded as integers, so when I compare I compare an unrounded value to rounded values. Anyway, I'll remove amount from the hash and it should work.

**Comment by scottrobertson** [comment]
Ah interesting. Nice catch

**Comment by rossdargan** [comment]
Ok, This should be good to go... not however it does not compare amount. This means two purchases on the same day will get caught out by the de-dupe. Until the bug with pynynab is resolved there isn't much I can do (for some reason -5.34 is reported as -6 by the library...)

Anyway, I'm going to modify the code to make the ynab_client long lived...

**Comment by scottrobertson** [comment]
I think we should leave this disabled for now then. A lot of people will have multiple purchases from the same shops on each day.

**Comment by scottrobertson** [comment]
Can you also merge master back into here to solve the README.md conflict.

**Comment by rossdargan** [comment]
I wonder if we should just totally abandon de-dupe. With the in memory stuff there really is no need for it anymore I don't think...

**Comment by scottrobertson** [comment]
It would be really nice to have it once we get the integer stuff working. But we can just leave it as a todo for now if you want?

**Pull request closed without merging**
